name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
api-version: 1.8
author: zPedroo_
main: com.zpedroo.voltzmachines.VoltzMachines
depend: [HolographicDisplays, MultiEconomy, ProtocolLib, PlotSquared]
load: POSTWORLD
commands:
  machines:
    aliases: [machine, maquinas, maquina]