name: Machines
description: Only a simple machines plugin.
version: 1.0
api-version: 1.8
author: zPedroo_
main: com.zpedroo.voltzmachines.VoltzMachines
depend: [HolographicDisplays, MultiEconomy, ProtocolLib, PlotSquared]
load: POSTWORLD
commands:
  machines:
    aliases: [machine, maquinas, maquina]