name: Machines
description: ${project.description}
version: 1.0
api-version: 1.16
author: zPedroo_
main: com.zpedroo.voltzmachines.VoltzMachines
depend: [WorldGuard, HolographicDisplays, Vault, ProtocolLib]
load: POSTWORLD
commands:
  machines:
    aliases: [machine, maquinas, maquina]